services:
  db:
    image: postgres:16.4
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: docuform_postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
